version: '3'
services:
  db:
    image: postgres:9.6.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGPASSWORD=${PGPASSWORD}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    networks:
      - minionet
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY}
      - MINIO_SECRET_KEY=${AWS_SECRET_KEY}
    command: server /export
  minio_setup:
    image: minio/mc
    entrypoint: [
      "sh", "-c",
      "sleep 5 &&\
       mc config host add minio http://172.19.0.2:9000 ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} &&\
       mc mb -p minio/cvs"
    ]
    networks:
      - minionet
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
    links:
      - minio
    depends_on:
      - minio
networks:
  minionet:
